echo ROM
del unodos.rom
echo SYS
del dos\errors.sys
del dos\tape.sys
del dos\unodos.sys
del src\unodos-0.sys
del src\unodos-1.sys
echo UNIT-TEST
del dos\test
echo CMD
del dos\attrib
del dos\bload
del dos\bsave
del dos\cd
del dos\chdir
del dos\color
del dos\copy
del dos\del
del dos\dir
del dos\dload
del dos\dsave
del dos\echo
del dos\erase
del dos\help
del dos\load
del dos\md
del dos\mkdir
del dos\mode
del dos\move
del dos\rd
del dos\ren
del dos\rename
del dos\rmdir
del dos\run
del dos\save
del dos\sload
del dos\ssave
del dos\ver
echo UNO
del dos\backup
del dos\unocfg
del dos\joy
del dos\keyb
del dos\restore
echo EXT
del dos\play
echo PROGRAMS
del programs\sampleap.p\unodos.app
echo EMU
del emu\esxmmc085.rom
del emu\sd_card.mmc
del emu\sd_card.hdf
del emu\48.rom
echo TAP
del src\unodos.tap
del flashmmc.tap
pause